spring.application.name=warpedcitadelauth

spring.config.import=optional:file:.env[.properties]
#spring.main.banner-mode=off
spring.output.ansi.enabled=ALWAYS

#Http Configuration
spring.mvc.apiversion.use.header=X-API-Version
app.cors.allowed-origins=${CORS}


#Email Configuration
mail.trap.token=${MAIL_TRAP_TOKEN}
spring.mail.host=${EMAIL_HOST}
spring.mail.port=${EMAIL_PORT}
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


#Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.connectionTimeout=${CONN_TIMEOUT}
spring.datasource.hikari.maximumPoolSize=${POOL_MAXSIZE}


#Security Configuration
spring.security.user.name=${SEC_USERNAME}
spring.security.user.password=${SEC_PASSWORD}
#logging.level.org.springframework.security=DEBUG


#JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}